### ISSUE TITLE
Dockerimage edit - map out the exact steps

### ISSUE THREAD

**Issue by timea** [Praqma/noops#25]
This is a subtask of #16.

Map out the exact steps of the setup on both the monitoring server and the monitored one. 

The delivery is a "How to set up monitoring" mini tutorial or a link to an existing one for both ubuntu and windows server.

**Comment by buep** [comment]
I'm happy to have this issue if I can get a write-up with just to small sections, of very few lines that explains:

* 1. section: what configuration file in Zabbix do I need to edit to add another host to be monitored? (it is not a Dockerfile, but a config file). Alternatively which CLI command do I need to call on Zabbix if that is better.
* 2. section: which command to I need to run my client (the server that needs to be monitored) for it to connect to Zabbix matching the config above.

**Comment by timea** [comment]
This handles #17 too.

**Comment by timea** [comment]
@buep Timebox ran out. The good news is that we allocated 2 hours extra for #17 that I have not used up. Could be used to research what DB changes we need for the server image. What do you think?

**Comment by buep** [comment]
yah, that is fine.

But please be aware you're supposed to implement monitoring of our infrastructure as examples. So don't monitor random digital ocean droplet... use our jenkinsubuntu as #17 say you should.

This issue was to figure it out, #17 to actual implement it.. that is how you split up the issue.

And as we earlier talked about.. I don't want a lot of docs, I want edited configuration files, docker-images etc. 
When we are done, we can clone this repo and run it again and get the same result... I don't want to run anything else that docker-compose up ... and then have the same result.

That have been stated as the overall goal - we need to focus on that.
