### ISSUE TITLE
Create the management droplet in DO

### ISSUE THREAD

**Issue by timea** [Praqma/noops#34]
Add the password to our password list.

**Comment by buep** [comment]
Document the management machine in the repo... so we know how it is created, you need to install docker-compose, docker-machine and docker.

**Comment by Andrey9kin** [comment]
I thought this might be useful https://github.com/Andrey9kin/digitalocean-cli - quite helpful when you need quickly create few instances and then use docker machine to provision them 

Like this (I usually use binary version instead of python script - see readme to find out how to build it)

digitalocean-cli create --size 16gb
digitalocean-cli list # get ip address for the next command
docker-machine create -d generic --generic-ip-address <ip from previous command> demo

**Comment by buep** [comment]
Thanks @Andrey9kin this is what we get from doing our research in public - we get good ideas from others :-)

**Comment by buep** [comment]
@timea I bumped the estimate to medium. Take some time to look at what Andrey gave us and see if it can help us.

**Comment by timea** [comment]
I could not use @Andrey9kin's tool, I filed an issue for that (https://github.com/Andrey9kin/digitalocean-cli/issues/1), So I will go and install the usual way.

**Comment by timea** [comment]
oh, by the way guys, why is @Andrey9kin removing our labels on close of an issue? :D @buep

**Comment by buep** [comment]
> oh, by the way guys, why is @Andrey9kin removing our labels on close of an issue? :D @buep

Bug in github I think...
