### ISSUE TITLE
Zabbix: Locate candidate Zabbix docker images

### ISSUE THREAD

**Issue by timea** [Praqma/noops#4]
In order to make an educated decision if we need to build our own Dockerfile for the Zabbix server, we need to investigate the extisting solutions out there. We need to 
- Locate the existing images
- Analyse if it fits our use case
- Conclude 
    - This decision will help to elaborate on #2 about the details of the implementation in regards of an extensible and generic container

**Comment by buep** [comment]
Estimate is timeboxed!

**Comment by buep** [comment]
Is there anything that needs to be done, related to #2 after your evaluation you have submitted? Part of the goal of this issue was to finish the grooming for briefing #2 - what is missing?

I guess there is nothing missing, except already groomed tasks and the found image seems to support the most.

If you agree - close this issue again.

**Comment by timea** [comment]
Yes, it seems it does.

**Comment by timea** [comment]
I did not want to take up #2 as it was not in the up next.

**Comment by buep** [comment]
> I did not want to take up #2 as it was not in the up next. 

#2 is also a briefing, and can never be worked on. We kept it because we wanted to make sure nothing was missing after you finished this issue.
So we can close #2 now.
