### ISSUE TITLE
Select the two pet servers to monitor, one of them containerized

### ISSUE THREAD

**Issue by timea** [Praqma/noops#7]

**Comment by buep** [comment]
Monitor jenkinsubuntu build slave for our code.praqma.net/ci using an agent. http://code.praqma.net/ci/computer/jenkinsubuntu/ 

Try agentless monitoring on dockerhost1 on our code.praqma.net/ci

Both these two slaves are pretty important for our Jenkins setup, so this is a good place to start.
Initially I remember this project started because we didn't notice a failure on our build infrastructure.
